/** Canonical list of environment variables used by this project. */

export const CLIENT_ENV_KEYS = [
  'VITE_SUPABASE_URL',
  'VITE_SUPABASE_ANON_KEY',
  'VITE_CLIENT_PORTAL_INTAKE_WEBHOOK_URL',
  'VITE_CLIENT_PORTAL_UPDATE_WEBHOOK_URL',
  'VITE_N8N_WF2_WEBHOOK_URL',
]

export const SERVER_ENV_KEYS = [
  'RESEND_API_KEY',
  'ADMIN_NOTIFY_EMAIL',
  'RESEND_FROM_EMAIL',
  'BUSINESS_POSTAL_ADDRESS',
  'LEAD_REPLY_TO_EMAIL',
  'LEAD_UNSUBSCRIBE_URL',
  'GOOGLE_SHEETS_WEBHOOK_SECRET',
  'GOOGLE_SHEETS_WEBHOOK_URL',
]

export const REQUIRED_ENV_KEYS = [
  'VITE_SUPABASE_URL',
  'VITE_SUPABASE_ANON_KEY',
  'GOOGLE_SHEETS_WEBHOOK_URL',
  'GOOGLE_SHEETS_WEBHOOK_SECRET',
]

export const REQUIRED_FOR_EMAIL_KEYS = [
  'RESEND_API_KEY',
  'RESEND_FROM_EMAIL',
  'ADMIN_NOTIFY_EMAIL',
]

export const ALL_ENV_KEYS = [...new Set([...CLIENT_ENV_KEYS, ...SERVER_ENV_KEYS])]
