/** Canonical list of environment variables used by this project. */

export const CLIENT_ENV_KEYS = [
  'VITE_SUPABASE_URL',
  'VITE_SUPABASE_ANON_KEY',
  'VITE_CLIENT_PORTAL_INTAKE_WEBHOOK_URL',
  'VITE_CLIENT_PORTAL_UPDATE_WEBHOOK_URL',
  'VITE_GOOGLE_MAPS_API_KEY',
  'VITE_GOOGLE_MAPS_MAP_ID',
]

export const SERVER_ENV_KEYS = [
  'RESEND_API_KEY',
  'RESEND_FROM_EMAIL',
  'GOOGLE_SHEETS_WEBHOOK_SECRET',
  'GOOGLE_SHEETS_WEBHOOK_URL',
  'GOOGLE_PLACES_API_KEY',
]

export const REQUIRED_ENV_KEYS = [
  'VITE_SUPABASE_URL',
  'VITE_SUPABASE_ANON_KEY',
  'GOOGLE_SHEETS_WEBHOOK_URL',
  'GOOGLE_SHEETS_WEBHOOK_SECRET',
]

export const REQUIRED_FOR_EMAIL_KEYS = [
  'RESEND_API_KEY',
  'RESEND_FROM_EMAIL',
]

export const ALL_ENV_KEYS = [...new Set([...CLIENT_ENV_KEYS, ...SERVER_ENV_KEYS])]
