import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

export default function AgentRunsPage() {
  const [state, setState] = useState({ runs: [], error: '' })
  useEffect(() => { async function load() { const m = await supabase.from('workspace_members').select('workspace_id').eq('status', 'active').order('created_at').limit(1).single(); if (m.error) return setState({ runs: [], error: m.error.message }); const r = await supabase.from('agent_runs').select('id, agent_key, command_level, status, input, output, error_message, created_at').eq('workspace_id', m.data.workspace_id).order('created_at', { ascending: false }); if (r.error) setState({ runs: [], error: r.error.message }); else setState({ runs: r.data || [], error: '' }) } load() }, [])
  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white md:px-10 md:py-12"><div className="mx-auto max-w-5xl"><Link className="text-sm font-semibold text-orange-300" to="/admin/workspace">← Workspace</Link><p className="mt-10 text-xs font-semibold uppercase tracking-[0.25em] text-orange-200">Operations</p><h1 className="mt-3 text-4xl font-semibold">Agent runs</h1><p className="mt-3 text-slate-400">Review queued and completed agent activity for this workspace.</p>{state.error && <p className="mt-6 text-rose-300">{state.error}</p>}<div className="mt-8 space-y-3">{state.runs.length ? state.runs.map(run => <article className="rounded-2xl border border-white/10 bg-white/[0.04] p-5" key={run.id}><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="font-semibold">{run.agent_key}</p><p className="mt-1 text-xs uppercase tracking-wide text-slate-500">{run.command_level} · {run.status}</p></div><time className="text-xs text-slate-500">{new Date(run.created_at).toLocaleString()}</time></div>{run.error_message && <p className="mt-3 text-sm text-rose-300">{run.error_message}</p>}</article>) : <p className="text-slate-500">No agent runs recorded yet.</p>}</div></div></main>
}
