import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

export default function KnowledgePage() {
  const [state, setState] = useState({ decisions: [], learnings: [], error: '' })
  useEffect(() => { async function load() { const member = await supabase.from('workspace_members').select('workspace_id').eq('status', 'active').order('created_at').limit(1).single(); if (member.error) return setState(s => ({ ...s, error: member.error.message })); const id = member.data.workspace_id; const [decisions, learnings] = await Promise.all([supabase.from('decisions').select('id, title, decision, status, created_at').eq('workspace_id', id).order('created_at', { ascending: false }), supabase.from('learnings').select('id, title, body, category, created_at').eq('workspace_id', id).order('created_at', { ascending: false })]); const failed = decisions.error || learnings.error; if (failed) setState(s => ({ ...s, error: failed.message })); else setState({ decisions: decisions.data || [], learnings: learnings.data || [], error: '' }) } load() }, [])
  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white md:px-10 md:py-12"><div className="mx-auto max-w-5xl"><Link className="text-sm font-semibold text-orange-300" to="/workspace">← Workspace</Link><p className="mt-10 text-xs font-semibold uppercase tracking-[0.25em] text-orange-200">Knowledge</p><h1 className="mt-3 text-4xl font-semibold">Decisions and learnings</h1><p className="mt-3 text-slate-400">Keep the reasoning and lessons behind the work visible to the team.</p>{state.error && <p className="mt-6 text-rose-300">{state.error}</p>}<div className="mt-10 grid gap-6 md:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><h2 className="text-2xl font-semibold">Decisions</h2><div className="mt-5 space-y-4">{state.decisions.length ? state.decisions.map(item => <article className="border-b border-white/10 pb-4" key={item.id}><p className="font-semibold">{item.title}</p><p className="mt-1 text-xs uppercase tracking-wide text-slate-500">{item.status}</p><p className="mt-3 text-sm text-slate-300">{item.decision}</p></article>) : <p className="text-sm text-slate-500">No decisions recorded yet.</p>}</div></section><section className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><h2 className="text-2xl font-semibold">Learnings</h2><div className="mt-5 space-y-4">{state.learnings.length ? state.learnings.map(item => <article className="border-b border-white/10 pb-4" key={item.id}><p className="font-semibold">{item.title}</p><p className="mt-3 text-sm text-slate-300">{item.body}</p></article>) : <p className="text-sm text-slate-500">No learnings recorded yet.</p>}</div></section></div></div></main>
}
