import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

export default function PlanningPage() {
  const [data, setData] = useState({ goals: [], initiatives: [], projects: [], error: '' })
  useEffect(() => { async function load() { const member = await supabase.from('workspace_members').select('workspace_id').eq('status', 'active').order('created_at').limit(1).single(); if (member.error) return setData(s => ({ ...s, error: member.error.message })); const id = member.data.workspace_id; const results = await Promise.all(['goals', 'initiatives', 'projects'].map(table => supabase.from(table).select('id, title, status').eq('workspace_id', id).order('updated_at', { ascending: false }))); const failed = results.find(r => r.error); if (failed) setData(s => ({ ...s, error: failed.error.message })); else setData({ goals: results[0].data || [], initiatives: results[1].data || [], projects: results[2].data || [], error: '' }) } load() }, [])
  const sections = [['Goals', data.goals], ['Initiatives', data.initiatives], ['Projects', data.projects]]
  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white md:px-10 md:py-12"><div className="mx-auto max-w-5xl"><Link className="text-sm font-semibold text-orange-300" to="/workspace">← Workspace</Link><p className="mt-10 text-xs font-semibold uppercase tracking-[0.25em] text-orange-200">Planning</p><h1 className="mt-3 text-4xl font-semibold">Direction and delivery</h1><p className="mt-3 text-slate-400">Connect strategic goals to initiatives, projects, campaigns, and tasks.</p>{data.error && <p className="mt-6 text-rose-300">{data.error}</p>}<div className="mt-10 grid gap-6 md:grid-cols-3">{sections.map(([label, items]) => <section className="rounded-3xl border border-white/10 bg-white/[0.04] p-5" key={label}><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{label}</h2><span className="text-2xl font-semibold text-orange-200">{items.length}</span></div><div className="mt-5 space-y-3">{items.length ? items.map(item => <div className="rounded-xl border border-white/10 bg-slate-900/60 p-3" key={item.id}><p className="font-medium">{item.title}</p><p className="mt-1 text-xs uppercase tracking-wide text-slate-500">{item.status}</p></div>) : <p className="text-sm text-slate-500">No records yet.</p>}</div></section>)}</div></div></main>
}
