import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

export default function NewProjectPage() {
  const [initiatives, setInitiatives] = useState([]); const [form, setForm] = useState({ initiative_id: '', title: '', description: '' }); const [error, setError] = useState(''); const navigate = useNavigate()
  useEffect(() => { async function load() { const m = await supabase.from('workspace_members').select('workspace_id').eq('status', 'active').order('created_at').limit(1).single(); if (m.error) return setError(m.error.message); const r = await supabase.from('initiatives').select('id,title').eq('workspace_id', m.data.workspace_id).order('title'); if (r.error) setError(r.error.message); else { setInitiatives(r.data || []); setForm(f => ({ ...f, initiative_id: r.data?.[0]?.id || '' })) } } load() }, [])
  async function submit(e) { e.preventDefault(); const m = await supabase.from('workspace_members').select('workspace_id').eq('status', 'active').order('created_at').limit(1).single(); const u = await supabase.auth.getUser(); const r = await supabase.from('projects').insert({ ...form, workspace_id: m.data.workspace_id, created_by: u.data.user.id }).select('id').single(); if (r.error) setError(r.error.message); else navigate('/admin/planning') }
  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white md:px-10 md:py-12"><div className="mx-auto max-w-3xl"><Link className="text-orange-300" to="/admin/planning">← Planning</Link><h1 className="mt-10 text-4xl font-semibold">New project</h1><form onSubmit={submit} className="mt-8 space-y-5 rounded-3xl border border-white/10 bg-white/[0.04] p-6"><select required value={form.initiative_id} onChange={e => setForm({ ...form, initiative_id: e.target.value })} className="w-full rounded-xl bg-slate-900 p-3">{initiatives.map(i => <option key={i.id} value={i.id}>{i.title}</option>)}</select><input required placeholder="Project title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="w-full rounded-xl bg-slate-900 p-3" /><textarea placeholder="Description" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} rows="5" className="w-full rounded-xl bg-slate-900 p-3" />{error && <p className="text-rose-300">{error}</p>}<button className="rounded-full bg-orange-300 px-5 py-3 font-semibold text-slate-950">Create project</button></form></div></main>
}
