import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

export default function NewVariantPage() {
  const { campaignId } = useParams(); const navigate = useNavigate()
  const [workspaceId, setWorkspaceId] = useState(null); const [form, setForm] = useState({ code: '', locale: 'en', working_title: '', transcript: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { supabase.from('workspace_members').select('workspace_id').eq('status', 'active').order('created_at').limit(1).single().then(({ data, error: e }) => e ? setError(e.message) : setWorkspaceId(data.workspace_id)) }, [])
  async function submit(e) { e.preventDefault(); setSaving(true); const { data: user } = await supabase.auth.getUser(); const result = await supabase.from('content_variants').insert({ ...form, code: form.code.toUpperCase(), campaign_id: campaignId, workspace_id: workspaceId, created_by: user.user.id }).select('id').single(); if (result.error) { setError(result.error.message); setSaving(false) } else navigate(`/admin/variants/${result.data.id}`) }
  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white md:px-10 md:py-12"><div className="mx-auto max-w-3xl"><Link className="text-sm font-semibold text-orange-300" to={`/admin/campaigns/${campaignId}`}>← Campaign</Link><h1 className="mt-10 text-4xl font-semibold">New content variant</h1><form onSubmit={submit} className="mt-8 space-y-5 rounded-3xl border border-white/10 bg-white/[0.04] p-6"><input required placeholder="Code (CWS-002-EN-MASTER)" value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} className="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-white" /><select value={form.locale} onChange={e => setForm({ ...form, locale: e.target.value })} className="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-white"><option value="en">English</option><option value="es">Spanish</option></select><input required placeholder="Working title" value={form.working_title} onChange={e => setForm({ ...form, working_title: e.target.value })} className="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-white" /><textarea placeholder="Transcript or script" rows="6" value={form.transcript} onChange={e => setForm({ ...form, transcript: e.target.value })} className="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-white" />{error && <p className="text-sm text-rose-300">{error}</p>}<button disabled={!workspaceId || saving} className="rounded-full bg-orange-300 px-5 py-3 text-sm font-semibold text-slate-950 disabled:opacity-50">{saving ? 'Creating…' : 'Create variant'}</button></form></div></main>
}
