import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

export default function ProjectDetailPage() {
  const { projectId } = useParams(); const [state, setState] = useState({ project: null, tasks: [], error: '' })
  useEffect(() => { async function load() { const m = await supabase.from('workspace_members').select('workspace_id').eq('status', 'active').order('created_at').limit(1).single(); if (m.error) return setState(s => ({ ...s, error: m.error.message })); const [project, tasks] = await Promise.all([supabase.from('projects').select('id,title,description,status').eq('id', projectId).eq('workspace_id', m.data.workspace_id).single(), supabase.from('tasks').select('id,title,status,priority,due_date').eq('project_id', projectId).eq('workspace_id', m.data.workspace_id).order('created_at', { ascending: false })]); if (project.error || tasks.error) setState(s => ({ ...s, error: (project.error || tasks.error).message })); else setState({ project: project.data, tasks: tasks.data || [], error: '' }) } load() }, [projectId])
  if (state.error) return <main className="min-h-screen bg-slate-950 p-8 text-white"><p className="text-rose-300">{state.error}</p></main>
  if (!state.project) return <div className="flex min-h-screen items-center justify-center bg-slate-950 text-slate-300">Loading project…</div>
  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white md:px-10 md:py-12"><div className="mx-auto max-w-4xl"><Link className="text-sm font-semibold text-orange-300" to="/admin/planning">← Planning</Link><p className="mt-10 text-xs uppercase tracking-[0.25em] text-orange-200">Project · {state.project.status}</p><h1 className="mt-3 text-4xl font-semibold">{state.project.title}</h1><p className="mt-4 leading-7 text-slate-300">{state.project.description || 'No description yet.'}</p><section className="mt-10 rounded-3xl border border-white/10 bg-white/[0.04] p-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">Linked tasks</h2><Link className="text-sm font-semibold text-orange-200" to="/admin/tasks">Manage tasks →</Link></div><div className="mt-5 space-y-3">{state.tasks.length ? state.tasks.map(task => <div className="rounded-xl border border-white/10 bg-slate-900/60 p-4" key={task.id}><p className="font-semibold">{task.title}</p><p className="mt-1 text-xs uppercase tracking-wide text-slate-500">{task.status} · priority {task.priority}</p></div>) : <p className="text-sm text-slate-500">No tasks linked to this project yet.</p>}</div></section></div></main>
}
