import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../../lib/supabase'

export default function TasksPage() {
  const [workspaceId, setWorkspaceId] = useState(null); const [tasks, setTasks] = useState([]); const [campaigns, setCampaigns] = useState([]); const [title, setTitle] = useState(''); const [campaignId, setCampaignId] = useState(''); const [error, setError] = useState('')
  async function load() { const member = await supabase.from('workspace_members').select('workspace_id').eq('status', 'active').order('created_at').limit(1).single(); if (member.error) return setError(member.error.message); setWorkspaceId(member.data.workspace_id); const [t, c] = await Promise.all([supabase.from('tasks').select('id, title, status, priority, due_date, campaign_id').eq('workspace_id', member.data.workspace_id).order('created_at', { ascending: false }), supabase.from('campaigns').select('id, code').eq('workspace_id', member.data.workspace_id).order('code')]); if (t.error || c.error) setError((t.error || c.error).message); else { setTasks(t.data || []); setCampaigns(c.data || []) } }
  useEffect(() => { load() }, [])
  async function addTask(e) { e.preventDefault(); const { data: user } = await supabase.auth.getUser(); const result = await supabase.from('tasks').insert({ workspace_id: workspaceId, title, campaign_id: campaignId || null, created_by: user.user.id }).select('id, title, status, priority, due_date, campaign_id').single(); if (result.error) setError(result.error.message); else { setTasks([result.data, ...tasks]); setTitle('') } }
  async function updateStatus(id, status) { const result = await supabase.from('tasks').update({ status }).eq('id', id).select('id, title, status, priority, due_date, campaign_id').single(); if (!result.error) setTasks(tasks.map(task => task.id === id ? result.data : task)) }
  const campaignMap = new Map(campaigns.map(campaign => [campaign.id, campaign.code]))
  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white md:px-10 md:py-12"><div className="mx-auto max-w-5xl"><Link className="text-sm font-semibold text-orange-300" to="/admin/workspace">← Workspace</Link><h1 className="mt-10 text-4xl font-semibold">Tasks</h1><form onSubmit={addTask} className="mt-6 flex flex-col gap-3 rounded-3xl border border-white/10 bg-white/[0.04] p-5 md:flex-row"><input required value={title} onChange={e => setTitle(e.target.value)} placeholder="What needs to happen?" className="flex-1 rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-white" /><select value={campaignId} onChange={e => setCampaignId(e.target.value)} className="rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-white"><option value="">No campaign</option>{campaigns.map(c => <option key={c.id} value={c.id}>{c.code}</option>)}</select><button disabled={!workspaceId} className="rounded-full bg-orange-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">Add task</button></form>{error && <p className="mt-4 text-rose-300">{error}</p>}<div className="mt-8 space-y-3">{tasks.map(task => <div className="flex flex-col justify-between gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-5 md:flex-row md:items-center" key={task.id}><div><p className="font-semibold">{task.title}</p><p className="mt-1 text-xs uppercase tracking-wide text-slate-500">{campaignMap.get(task.campaign_id) || 'Unlinked'} · Priority {task.priority}</p></div><select value={task.status} onChange={e => updateStatus(task.id, e.target.value)} className="rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-sm text-slate-200"><option value="todo">Todo</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="review">Review</option><option value="completed">Completed</option></select></div>)}</div></div></main>
}
